language: python

python:
- "2.7"
- "3.6"

before_install:
- pip install --upgrade pip
- pip install Cython --install-option="--no-cython-compile"

install:
- pip install --process-dependency-links --no-cache-dir -r requirements-dev.txt

script:
- invoke test
