name: docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.docs@v2.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doc_url: https://arpastrana.github.io/compas_cem
