on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: compas-dev/compas-actions.build@v1.0.0
        with:
          test_lint: true
          test_compas: true
      - uses: NuGet/setup-nuget@v1.0.5
      - name: Install dependencies
        run: |
          choco install ironpython --version=2.7.8.1

      - name: 🦗 Build grasshopper components
        uses: compas-dev/compas-actions.ghpython_components@v1
        with:
          source: src/compas_cem/ghpython/components
          target: src/compas_cem/hpython/components/ghuser

      - name: 💃 Build release
        if: success() && startsWith(github.ref, 'refs/tags')
        run: |
          python setup.py clean --all sdist bdist_wheel

      - name: 📦 Publish release to PyPI
        if: success() && startsWith(github.ref, 'refs/tags')
        run: |
            twine check dist/*
            twine upload dist/* --skip-existing
        env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.PYPI }}
